### ISSUE TITLE
VCF filtering issue

### ISSUE THREAD

**Issue by hannah-happ** [tfwillems/HipSTR#94]
I am trying to filter my HipSTR VCF but am getting the following error:

`Traceback (most recent call last):
  File "/scratch/ucgd/lustre-work/quinlan/u6055472/storage/tools/HipSTR/scripts/filter_vcf.py", line 233, in <module>
    main()
  File "/scratch/ucgd/lustre-work/quinlan/u6055472/storage/tools/HipSTR/scripts/filter_vcf.py", line 94, in main
    vcf_writer    = vcf.Writer(sys.stdout, vcf_reader)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/ucgd/lustre-work/quinlan/u6055472/storage/tools/miniconda3/lib/python3.11/site-packages/vcf/parser.py", line 642, in __init__
    self.writer = csv.writer(stream, delimiter="\t",
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

I'm using the default parameters (below), and get the same error with my VCF and the test VCF in the HipSTR test directory

`python ${scripts}/filter_vcf.py --vcf ${VCF_DIR}/str_calls.vcf --min-call-qual 0.9 --max-call-flank-indel 0.15 --max-call-stutter 0.15 --min-call-allele-bias -2 --min-call-strand-bias -2`

Any suggestions? Thanks!

**Comment by hannah-happ** [comment]
moving this to the gymrek-lab forked HipSTR
